Maint emergency
rbertoche/space-station-14 pull request #129
Opened 2024-08-25 18:41 UTC by AgentePanela

## Introdução sobre o PR

Modifica/repensa o console de comunicações e retira acesso de manutenção dos assistentes (como parte da mecanica)

## Motivação para a mudança

o console atual é muito "ruim" e poderia ter muitos mais recursos

## Descrição da mudança em si

Retira o acesso de manutenção dos assistentes
Adiciona um novo tipo de botão, botao amarelo (adicionando ele no stylenano.cs)
Modifica o codigo de endround, agora é possivel dar um motivo pelo endround e mudar o titulo (sem afetar os outros codigos)
Agora da para botar um motivo na hora de chamar a evacuação (opcional)
Adiciona textos para cada "sessão" do console de comunicações
Adiciona o botão de falar com a centcom (alertara os admins parecido com o telefone vermelho)
Adiciona o botão de alterar o acesso das manutençãos de emergencia, junto com um anuncio
Agora da para diferenciar (re)call da evacuação do comando e dos admins (se for um admin, aparecera que a centcom chamou o shuttle ou cancelou ele)

## Media

![video](https://cdn.discordapp.com/attachments/1139279106123518073/1277334924726243399/2024-08-25_15-06-04.mp4?ex=66ccca59&is=66cb78d9&hm=2bdc7ef1d7989e6bdad2ed23bc4cc218c825573804e1f0cdcd544408559e1f94&)

![image](https://github.com/user-attachments/assets/9e2697a9-e4f2-4eed-8a22-03ecb37b4f06)

**Changelog**

eu ja fiz minha entrada manualmente

2024-08-25 18:52 UTC, VMSolidus requested changes
These are just a few suggestions, all except inverting ifs in a while loop are just style improvements.

2024-08-25 18:52 UTC, VMSolidus commented on Content.Client/Communications/UI/CommunicationsConsoleBoundUserInterface.cs
> +        }
```suggestion
        public void MaintEmergencyButtonPressed()
        {
            SendMessage(new CommunicationsConsoleToggleEmergencyMaintMessage());
        }

        public void CentCommButtonPressed()
        {
            SendMessage(new CommunicationsConsoleCentCommButtonMessage());
        }
```

2024-08-25 18:52 UTC, VMSolidus commented on Content.Server/Communications/CommunicationsConsoleComponent.cs
> +        public double ToggleAcessDelay = 5;
```suggestion
        [DataField]
        public double ToggleAcessTimer;

        [DataField]
        public double ToggleAcessDelay = 5;
```

2024-08-25 18:52 UTC, VMSolidus commented on Content.Server/Communications/CommunicationsConsoleSystem.cs
>                  return;
```suggestion
            if (!EntityManager.TryGetComponent(message.Actor, out ActorComponent? actor)
                || !CanCallOrRecall(comp))
                return;
```

2024-08-25 18:52 UTC, VMSolidus commented on Content.Server/Communications/CommunicationsConsoleSystem.cs
> +            var mob = message.Actor;
```suggestion
            if ((_timing.CurTime.TotalSeconds - comp.ToggleAcessTimer) < comp.ToggleAcessDelay) //coldown
                return;

            var mob = message.Actor;
```

2024-08-25 18:52 UTC, VMSolidus commented on Content.Server/Communications/CommunicationsConsoleSystem.cs
> +            var mob = message.Actor;
```suggestion
            if (!EntityManager.TryGetComponent(message.Actor, out ActorComponent? actor))
                return;

            var mob = message.Actor;
```

2024-08-25 18:52 UTC, VMSolidus commented on Content.Server/Communications/CommunicationsConsoleSystem.cs
> +                }
```suggestion
                if (!TryGetNetEntity(doorUid, out var netEntity) 
                    || !TryGetEntityData(netEntity.Value, out var entityUid, out var entityData)
                    || !_maintDoorPrototypeList.Contains(entityData.EntityPrototype!.ID))
                    || !TryComp<AirlockComponent>(doorUid, out var airlock)
                    continue;

                _airlock.ToggleEmergencyAccess(doorUid, airlock);
```

2024-08-25 18:52 UTC, VMSolidus commented on Content.Shared/Communications/SharedCommunicationsConsoleComponent.cs
> +    }
```suggestion
    [Serializable, NetSerializable]
    public sealed class CommunicationsConsoleToggleEmergencyMaintMessage : BoundUserInterfaceMessage { }

    [Serializable, NetSerializable]
    public sealed class CommunicationsConsoleCentCommButtonMessage : BoundUserInterfaceMessage { }
```

2024-08-27 20:36 UTC, rbertoche commented
Ahh isso eu ja tinha visto por alto
se nao tiver nenhum bug a gente pode manter
a Solidus review! nice, that makes it more solid! :P

2024-08-27 20:37 UTC, merged