Adicionada novas receitas, bebidas e pequena mudanças
rbertoche/space-station-14 pull request #56
Opened 2024-02-14 02:23 UTC by LaryNevesPR

## About the PR

- Foram adicionadas receitas de comidas que já estão no jogo, mas não haviam forma de faze-las de fato.
- Foi adicionado uma nova bebida: Bubble Tea ao jogo. A bebida foi retirada do Delta-V.
- Algumas comida rebalanciadas
## Why / Balance

- Há muitas comidas legais no jogo que não há nenhuma forma de faze-las atualmente. Achei interessante dá mais variedades as comidas da estação.
- Valores de nutrientes alterados de algumas comidas para tentar fazer sentido com a quantidade de ingredientes utilizados na receita. Provavelmente ainda terei que rebalanciar

2024-02-14 08:38 UTC, rbertoche commented
Nossa que ótimo!
vou revisar agora.
Se quiser, vc pode discutir as mudanças no discord e até me pedir pra fazer pull por lá mesmo, sem precisar abrir PR.
Agora, se for abrir PR fica melhor se você evitar mudar muitas coisas em um commit só. Mas não faz mal porque quase tudo que você mudou eu vou querer mergir. Vou fazer uns pedidos de edição!

2024-02-14 08:50 UTC, rbertoche requested changes

2024-02-14 08:50 UTC, rbertoche commented on Resources/Prototypes/Entities/Objects/Consumable/Food/Baked/misc.yml
Aqui você alterou os campos do da entidade FoodBakedBase, não sei se isso foi intencional mas você vai alterar a quantidade de nutrientes em todos os FoodBakedBase que não definirem uma solução própria, particular.
Então é melhor reverter essas 2 linhas 15 e 18, não vai precisar mudar tantos, ou então deixa pra mudar essas coisas depois desse PR.

2024-02-14 08:50 UTC, rbertoche commented on Resources/Prototypes/Entities/Objects/Consumable/Food/snacks.yml
Isso daqui também não vai ser o caso pq pelo q eu entendi esse Extractable vai alterar o resultado de botar barra de chocolate no mixer. Isso vai impedir as pessoas de obterem Teobromina por exemplo e remove uma das fontes de pó de cacau. Vamos pensar outra forma de fazer chocolate líquido, provavelmente uma receita envolvendo pó de cacau ou algo do tipo.

2024-02-14 08:50 UTC, rbertoche commented on Resources/Prototypes/EstacaoPirata/Reagents/Consumable/Drinks/drinks.yml
Eu fiquei na dúvida se você tava pensando nisso mais como um ingrediente pra futuras receitas, ou um drink. Se for um drink acho melhor chamar apenas de chocolate mesmo ou, se preferir, chocolate quente. Chocolate líquido pra mim ou é chocolate derretido, ou a massa do chocolate duranto o preparo antes de ser solidificado, mas aí não seria bem um drink.

2024-02-14 08:50 UTC, rbertoche commented
É isso. Se vc preferir me pede pra fazer as mudanças eu mesmo, pra mim dá na mesma. Qualquer coisa vem na minha dm ou me pinga lá no discord.

2024-02-14 09:03 UTC, rbertoche commented
Ah já ia esquecer. Você tem que especificar o que não é de sua autoria em algum lugar, em um arquivo texto.
Pega como exemplo esse [commit do Criso](https://github.com/rbertoche/space-station-14/commit/cf09f5326fa2ab022c6dcee418e4c3b9eb794bc0) ou [esse do Dasprino](https://github.com/rbertoche/space-station-14/commit/8ece9d4d23993f6b411079f53f4c988b5c2d0dcd).
Não precisa achar a PR de tudo, o importante é identificar o autor e de onde vc pegou, Delta V no caso né?
Se vc usar o comando git log passando o arquivo em questão no repositório do qual vc pegou o arquivo, vc vai ver o histórico de mudanças dele.

2024-02-14 17:32 UTC, LaryNevesPR commented on Resources/Prototypes/Entities/Objects/Consumable/Food/snacks.yml
O Extractable ali permite utilizar a barra de chocolate no Reagent grinder, nenhum Snack era permitido. O que eu fiz foi permitir somente o chocolate ser possível usar o Reagent grinder e permiti ser usado para liquido tambem. Ainda é possivel triturar ele para pegar a Theobromine.

2024-02-14 17:32 UTC, LaryNevesPR commented on Resources/Prototypes/Entities/Objects/Consumable/Food/Baked/misc.yml
Ok! irei reverter!

2024-02-14 17:42 UTC, LaryNevesPR commented
Ok! Irei fazer as mudanças e colocar o autor. Atualmente há uma reação para fazer a barra de chocolate envolvendo o cacau em pó, leite e açucar. Talvez eu poderia inverter, trocar a reação para fazer chocolate derretido invés de chocolate em barra e pensar em outra forma de fazer ele em barra.
Não sei se é possivel utilizar o frio para fazer alguma receita, o que seria o ideal.

2024-02-14 21:32 UTC, LaryNevesPR commented
Adicionei os créditos ao autor, adicionei receitas novas e troquei o chocolate para chocolate quente.
Adicionei uma reação onde utiliza cacau em pó e açúcar para fazer chocolate quente. A reação é ativada somente depois que a temperatura do beaker chega a 344 no microondas.

2024-02-15 15:28 UTC, rbertoche commented on Resources/Prototypes/Entities/Objects/Consumable/Food/snacks.yml
Ah snacks não entra né. Ok.
Mas como você vai obter a teobromina se o Extractable da barra de chocolate tiver gerando apenas chocolate derretido puro?
Ainda prefiro que você só tire esse extractable. Derreter no grinder não tá legal. E agora que tem uma receita melhor pra fazer não precisa mais disso

2024-02-15 15:29 UTC, rbertoche commented on Resources/Prototypes/EstacaoPirata/Reagents/Consumable/Drinks/drinks.yml
Não entendi porquê chocolate derretido sinceramente. A receita claramente não envolve derreter chocolate!

2024-02-15 15:30 UTC, rbertoche commented on Resources/Prototypes/Recipes/Reactions/drinks.yml
Isso aqui ficou bom, só faltou adicionar leite, e de fato gerar Chocolate Quente, não derretido.

2024-02-18 04:43 UTC, rbertoche commented on Resources/Prototypes/Recipes/Reactions/drinks.yml
Resolve isso aqui quando der

2024-02-18 04:46 UTC, rbertoche commented on Resources/Prototypes/EstacaoPirata/Reagents/Consumable/Drinks/drinks.yml
Ainda tá com esse problema. Faz o Drink como Chocolate ou Chocolate quente.
Aí se vc quiser mt adicionar um reagente, adiciona, mas chocolate derretido não pode ser um drink, não deve morar em Resources/Prototypes/EstacaoPirata/Reagents/Consumable/Drinks

2024-02-18 04:46 UTC, rbertoche commented
Seria bom não adicionar conteudo antes de resolver as questões que eu pedi!

2024-02-19 14:48 UTC, merged

2024-02-19 14:48 UTC, rbertoche commented
Valeu!